### ISSUE TITLE
How to draw the pretty figure?

### ISSUE THREAD

**Issue by dragen1860** [znxlwm/pytorch-MNIST-CelebA-GAN-DCGAN#4]
Hi, dear author:
I found your figure in readme.md looks pretty good:
![image](https://user-images.githubusercontent.com/4252555/42300777-aba5dc28-8044-11e8-96c5-532756e3b380.png)
I wonder what tool u used to make it? .

**Comment by znxlwm** [comment]
I used PowerPoint 2013
